/** Public URL for the GradEzy logo (`client/public/gradezy-logo.png`) */
export const GRADEZY_LOGO_URL = '/gradezy-logo.png';

/** Absolute logo URL for print / new windows (same origin as the app). */
export function gradezyLogoAbsoluteUrl() {
  if (typeof window === 'undefined') return GRADEZY_LOGO_URL;
  return `${window.location.origin}${GRADEZY_LOGO_URL}`;
}

/** Navy / orange wordmark (matches in-app branding). */
export const GRADEZY_BRAND_NAVY = '#1E3A8A';
export const GRADEZY_BRAND_ORANGE = '#FB923C';

/** Footer line for generated print/PDF views. */
export const GRADEZY_PRINT_FOOTER = 'Generated by GradEzy — Fourise Software Solutions';

/** CSS for the logo + Grad/Ezy row in print `<style>` blocks. */
export const GRADEZY_BRAND_PRINT_CSS = `
  .brand-row { display: flex; align-items: center; gap: 12px; margin-bottom: 12px; }
  .brand-logo { width: 44px; height: 44px; object-fit: contain; flex-shrink: 0; }
  .brand { font-size: 28px; font-weight: 800; line-height: 1; }
  .brand .a { color: ${GRADEZY_BRAND_NAVY}; }
  .brand .b { color: ${GRADEZY_BRAND_ORANGE}; }
`.trim();

/**
 * HTML fragment for print windows: logo + Grad/Ezy wordmark.
 * @param {string} logoUrl — use {@link gradezyLogoAbsoluteUrl}
 */
export function brandMarkPrintHtml(logoUrl) {
  const safe = String(logoUrl)
    .replace(/&/g, '&amp;')
    .replace(/"/g, '&quot;');
  return `<div class="brand-row"><img src="${safe}" alt="" class="brand-logo" width="44" height="44" /><div class="brand"><span class="a">Grad</span><span class="b">Ezy</span></div></div>`;
}
